
linter:
  rules:
    annotate_overrides: false
    avoid_setters_without_getters: false
    camel_case_extensions: true
    camel_case_types: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    library_prefixes: false
    lines_longer_than_80_chars: false
    prefer_constructors_over_static_methods: false
    prefer_relative_imports: true
    prefer_single_quotes: false
    sort_constructors_first: false
    sort_pub_dependencies: false
    valid_regexps: true



